### ISSUE TITLE
Extend SetupCommand to create parameters.yml

### ISSUE THREAD

**Issue by ingowalther** [ingowalther/image-minify-api#7]
Let the SetupCommand create the parameters.yml by questioning the user for the Database-Informations.

**Comment by xRahul** [comment]
Hey @ingowalther 

I'll take this one!

**Comment by ingowalther** [comment]
@xRahul thank you!

**Comment by luchianenco** [comment]
as I understand = the parameters.yml will be created during composer install, so do you mean to update parameters.yml db configuration?

**Comment by ingowalther** [comment]
At the moment you have to copy the parameters.yml.dist by hand. 

It would be cool if the parameters.yml is created while executing the setup command. But there is a issue that the container requires the existence of the parameters.yml

**Comment by luchianenco** [comment]
I think that it is possible to make it automatic by https://github.com/Incenteev/ParameterHandler
and updating composer.json file, then during composer install the parameters.yml will created and you will be prompted to enter parameters or to use the default ones

**Comment by ingowalther** [comment]
Oh that looks great! I also like the idea to execute the installation as composer post-install script. It looks like the best an cleanest solution to me.

**Comment by luchianenco** [comment]
ready for PR, but don't see if you merged the previous PR

**Comment by ingowalther** [comment]
Your solution looks good! But maybe it is a good idea to create a seperate config for the "binary_path" and "command" elements and copy a dist file after composer install. It the most use-cases you will use the default and it is a little bit annoying to push enter for every element. What do you think?

**Comment by ingowalther** [comment]
Or maybe we wait till they will merge https://github.com/Incenteev/ParameterHandler/pull/95

**Comment by xRahul** [comment]
This looks to be the good solution.. I'll leave it to @surgun9 then

**Comment by luchianenco** [comment]
Well, of course we can split config, but you do it only once and you need just to press enter if you will use default value....later when parametersHandler will be updated we can update the composer.json

**Comment by ingowalther** [comment]
Okay. That is fine for me at the moment!

**Comment by luchianenco** [comment]
so what is your decision?

**Comment by ingowalther** [comment]
I will merge #10 later. It is okay for me at the moment.
Thank you for your work!

**Comment by luchianenco** [comment]
ok, you are welcome

**Comment by ingowalther** [comment]
Done with #10!
